# Data Pre - Processing
## Standard Scaler

In [1]:
from sklearn import datasets
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target

In [2]:
X = df.iloc[:, [0,1,2, 3]].values
y = df.iloc[:, 4].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
# Usando el modelo de SkLearn
sc = StandardScaler()

X_trainSC = sc.fit(X_train)
print(sc.mean_)
print(sc.scale_)

X_trainSC = sc.transform(X_train)
        
print(X_trainSC)

In [3]:
class StandarScaler:
    """ 
    Standardize features by removing the mean and scaling to unit variance. 
    z = (x - MEAN) / DESV EST 
    """
    def __init__(self):
        pass

    def fit(self, X):
        X = pd.DataFrame(X)
        self.mean = X.mean(axis = 0).to_numpy()
        self.std = X.std(axis = 0).to_numpy()
        
    def transform(self, X):
        X -= self.mean
        X /= self.std
        return X 
    
    def fitTransform(self, X):
        self.fit(X)
        df = self.transform(X)
        return df 


In [6]:
sc = StandarScaler()
nuevo = sc.fit(X_train)
nuevo = sc.transform(X_train)
nuevo2 = sc.fitTransform(X_train)


FIT
[ 1.20935008e-15 -6.09631393e-17  8.12841857e-17 -3.39014531e-16]
[1. 1. 1. 1.]

TR
[ 1.20935008e-15 -6.09631393e-17  8.12841857e-17 -3.39014531e-16]
[1. 1. 1. 1.]

FIT
[ 2.37904934e-17  1.33821525e-17  2.97381167e-17 -5.15460690e-17]
[1. 1. 1. 1.]

TR
[ 2.37904934e-17  1.33821525e-17  2.97381167e-17 -5.15460690e-17]
[1. 1. 1. 1.]


In [7]:
nuevo

array([[ 1.53708703e-02, -1.18721172e-01,  2.24119566e-01,
         3.54205681e-01],
       [-9.93982948e-02, -1.03573988e+00,  1.13051463e-01,
        -2.97075732e-02],
       [ 1.04829336e+00, -1.18721172e-01,  9.46062240e-01,
         1.12203219e+00],
       [-1.36185911e+00,  3.39788182e-01, -1.38636794e+00,
        -1.30941842e+00],
       [ 1.16306252e+00,  1.10533505e-01,  7.23926033e-01,
         1.37797436e+00],
       [-1.01755162e+00,  1.02755221e+00, -1.21976578e+00,
        -7.97534082e-01],
       [-5.58474955e-01,  1.48606157e+00, -1.27529983e+00,
        -1.30941842e+00],
       [-1.01755162e+00, -2.41126794e+00, -1.64618796e-01,
        -2.85649743e-01],
       [ 7.03985861e-01, -1.18721172e-01,  9.46062240e-01,
         7.38118935e-01],
       [ 9.33524191e-01,  5.69042859e-01,  1.05713034e+00,
         1.63391653e+00],
       [ 1.30140035e-01, -1.95275859e+00,  6.68391981e-01,
         3.54205681e-01],
       [ 9.33524191e-01, -1.26499456e+00,  1.11266440e+00,
      

In [8]:
nuevo2

array([[ 1.53708703e-02, -1.18721172e-01,  2.24119566e-01,
         3.54205681e-01],
       [-9.93982948e-02, -1.03573988e+00,  1.13051463e-01,
        -2.97075732e-02],
       [ 1.04829336e+00, -1.18721172e-01,  9.46062240e-01,
         1.12203219e+00],
       [-1.36185911e+00,  3.39788182e-01, -1.38636794e+00,
        -1.30941842e+00],
       [ 1.16306252e+00,  1.10533505e-01,  7.23926033e-01,
         1.37797436e+00],
       [-1.01755162e+00,  1.02755221e+00, -1.21976578e+00,
        -7.97534082e-01],
       [-5.58474955e-01,  1.48606157e+00, -1.27529983e+00,
        -1.30941842e+00],
       [-1.01755162e+00, -2.41126794e+00, -1.64618796e-01,
        -2.85649743e-01],
       [ 7.03985861e-01, -1.18721172e-01,  9.46062240e-01,
         7.38118935e-01],
       [ 9.33524191e-01,  5.69042859e-01,  1.05713034e+00,
         1.63391653e+00],
       [ 1.30140035e-01, -1.95275859e+00,  6.68391981e-01,
         3.54205681e-01],
       [ 9.33524191e-01, -1.26499456e+00,  1.11266440e+00,
      